name: Cherry-pick on Comment

on:
  push:
    branches:
      - test
  
# Skip job run if PR updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create a new branch from the release branch
        run: |
          git fetch origin cherry-pick-workflow-release-branch
          git checkout cherry-pick-workflow-release-branch
          git pull origin cherry-pick-workflow-release-branch
          git checkout -b cherry-pick-workflow-release-branch-test

      - name: Cherry-pick the merge commit
        id: cherry-pick
        run: |
          set -e
          git branch --show-current
          git cherry-pick 7931357 || echo "conflict" > conflict.txt
        continue-on-error: true

      - name: Check for conflicts
        id: check-conflicts
        run: |
          if [ -f conflict.txt ]; then
            echo "CONFLICT=true" >> $GITHUB_ENV
          else
            echo "CONFLICT=false" >> $GITHUB_ENV
          fi

      - name: Handle conflict and exit
        if: env.CONFLICT == 'true'
        run: |
          git cherry-pick --abort
          git checkout cherry-pick-workflow-release-branch
          git branch -D cherry-pick-workflow-release-branch-test
          exit 1

      - name: Push the new branch
        run: git push origin cherry-pick-workflow-release-branch-test

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: cherry-pick-workflow-release-branch
          head: cherry-pick-workflow-release-branch-test
          title: Test Title
          body: Test Body
